username: admin
password: NokiaSrl1!
log-file: ./gnmic.log
tls-ca: ./clab-elk/.tls/ca/ca.pem
tls-cert: ./clab-elk/.tls/spine2/spine2.pem
tls-key: ./clab-elk/.tls/spine2/spine2.key
skip-verify: true
timeout: 30s
encoding: json_ietf

